[package]
name = "toy-blog"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
actix-web-httpauth = "0.6.0"
anyhow = "1.0.57"
chrono = { version = "0.4.19", default-features = false, features = ["std", "clock", "libc", "time", "serde"] }
clap = { version = "3.2.5", features = ["derive"] }
fern = { version = "0.6.1", features = ["colored"] }
log = "0.4.17"
once_cell = "1.12.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
