[package]
name = "toy-blog"
version = "0.4.10"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.2"
actix-web = "4.1.0"
actix-web-httpauth = "0.8.0"
addr = { version = "0.15.4", features = ["serde"] }
anyhow = "1.0.62"
chrono = { version = "0.4.22", default-features = false, features = ["std", "clock", "libc", "time", "serde"] }
clap = { version = "3.2.17", features = ["derive"] }
fern = { version = "0.6.1", features = ["colored"] }
log = "0.4.17"
once_cell = "1.13.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.83"
strum = { version = "0.24.1", features = ["derive"] }
telnet-codec = "0.1.0"
tokio = "1.20.1"
# for telnet-codec
tokio-util = "0.6.10"
