[package]
name = "toy-blog"
version = "0.5.2"
edition = "2021"
# it's used
metadata = { cargo-udeps = { ignore = [["thiserror"]] } }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.4.0"
actix-web-httpauth = "0.8.1"
anyhow = "1.0.75"
chrono = { version = "0.4.31", default-features = false, features = ["std", "clock", "libc", "serde"] }
clap = { version = "4.4.7", features = ["derive"] }
fern = { version = "0.6.2", features = ["colored"] }
fs2 = { version = "0.4.3" }
log = "0.4.20"
maplit = "1.0.2"
once_cell = "1.18.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["time", "macros"] }
toy-blog-endpoint-model = { path = "../toy-blog-endpoint-model" }

[features]
unstable_activitypub = []
