[package]
name = "toy-blog"
version = "0.5.2"
edition = "2021"
# it's used
metadata = { cargo-udeps = { ignore = [["thiserror"]] } }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.3.1"
actix-web-httpauth = "0.8.0"
anyhow = "1.0.72"
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock", "libc", "time", "serde"] }
clap = { version = "4.3.14", features = ["derive"] }
fern = { version = "0.6.2", features = ["colored"] }
fs2 = { version = "0.4.3" }
log = "0.4.19"
maplit = "1.0.2"
once_cell = "1.18.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["time", "macros"] }
toy-blog-endpoint-model = { path = "../toy-blog-endpoint-model" }

[features]
unstable_activitypub = []
