[package]
name = "toy-blog"
version = "0.5.0"
edition = "2021"
# it's used
metadata = { cargo-udeps = { ignore = [["thiserror"]] } }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.3.1"
actix-web-httpauth = "0.8.0"
anyhow = "1.0.71"
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock", "libc", "time", "serde"] }
clap = { version = "4.3.1", features = ["derive"] }
fern = { version = "0.6.2", features = ["colored"] }
log = "0.4.18"
maplit = "1.0.2"
once_cell = "1.17.2"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.40"
tokio = "1.28.2"
toy-blog-endpoint-model = { path = "../toy-blog-endpoint-model" }
