[package]
name = "toy-blog"
version = "0.4.15"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.3.1"
actix-web-httpauth = "0.8.0"
addr = { version = "0.15.6", features = ["serde"] }
anyhow = "1.0.70"
chrono = { version = "0.4.24", default-features = false, features = ["std", "clock", "libc", "time", "serde"] }
clap = { version = "4.2.2", features = ["derive"] }
fern = { version = "0.6.2", features = ["colored"] }
log = "0.4.17"
maplit = "1.0.2"
once_cell = "1.17.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
strum = { version = "0.24.1", features = ["derive"] }
telnet-codec = "0.1.0"
thiserror = "1.0.40"
tokio = "1.27.0"
# for telnet-codec
tokio-util = "0.6.10"
toy-blog-endpoint-model = { path = "../toy-blog-endpoint-model" }
