[package]
name = "toy-blog"
version = "0.5.3"
edition = "2021"
# it's used
metadata = { cargo-udeps = { ignore = [["thiserror"]] } }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.0"
actix-service = "2.0.2"
actix-web = "4.5.1"
actix-web-httpauth = "0.8.1"
anyhow = "1.0.82"
chrono = { version = "0.4.38", default-features = false, features = ["std", "clock", "libc", "serde"] }
clap = { version = "4.5.4", features = ["derive"] }
fern = { version = "0.6.2", features = ["colored"] }
fs2 = { version = "0.4.3" }
log = "0.4.21"
maplit = "1.0.2"
once_cell = "1.19.0"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
strum = { version = "0.26.2", features = ["derive"] }
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["time", "macros"] }
toy-blog-endpoint-model = { path = "../toy-blog-endpoint-model" }

[features]

[dev-dependencies]
tempfile = "3.10.1"
tokio = { version = "1.37.0", features = ["macros", "rt"] }
