[package]
name = "toy-blog-telnet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-server = "2.2.0"
actix-service = "2.0.2"
actix-web-codegen = "4.2.0"
anyhow = "1.0.70"
bytes = "1.4.0"
clap = { version = "4.2.2", features = ["derive"] }
fern = "0.6.2"
log = "0.4.17"
once_cell = "1.17.1"
reqwest = { version = "0.11.16", default-features = false, features = ["gzip", "deflate", "brotli", "rustls-tls", "json"] }
telnet-codec = "0.1.0"
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.7", features = ["codec"] }
toy-blog-endpoint-model = { version = "0.1.0", path = "../toy-blog-endpoint-model" }
url = "2.3.1"
