name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            runner: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
            test: true
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            test: true
          - target: x86_64-apple-darwin
            runner: macos-latest
            test: true
          # Oracle Cloud Infrastructure
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup toolchain
      run: |
        rustup target add '${{ matrix.target }}'
    - name: Install musl-tools
      id: setup-x64-musl
      run: |
        sudo apt update && sudo apt install musl-tools
      if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
    - name: Install gcc-aarch64-linux-gnu
      id: setup-aarch64-linux
      run: |
        sudo apt update && sudo apt install gcc-aarch64-linux-gnu
      if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
    - name: Install gcc-mingw-w64-x86-64
      id: setup-mingw-w64
      run: |
        sudo apt update && sudo apt install gcc-mingw-w64-x86-64
      if: ${{ matrix.target == 'x86_64-pc-windows-gnu' }}
    - name: Download cache
      uses: Swatinem/rust-cache@v2
      with:
        key: '${{ matrix.target }}'
        prefix-key: '${{ env.CI_RUST_CACHE_VERSION }}'
      env:
        CI_RUST_CACHE_VERSION: v0
    - name: Compile check
      run: cargo check --verbose --target '${{ matrix.target }}'
    - name: Lint with clippy
      run: cargo clippy --verbose --target '${{ matrix.target }}'
    - name: Run tests
      run: cargo test --verbose --target '${{ matrix.target }}'
      if: ${{ matrix.test == true }}
