name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            runner: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: x86_64-apple-darwin
            runner: macos-latest
          # Oracle Cloud Infrastructure
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup toolchain
      run: |
        rustup target add '${{ matrix.target }}'
    - name: Install musl-tools
      id: setup-x64-musl
      run: |
        apt install musl-tools
      if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
    - name: Install gcc-aarch64-linux-gnu
      id: setup-aarch64-linux
      run: |
        apt install gcc-aarch64-linux-gnu
      if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
    - name: Download cache
      uses: Swatinem/rust-cache@v2
      with:
        key: '${{ matrix.target }}'
        prefix-key: '${{ env.CI_RUST_CACHE_VERSION }}'
      env:
        CI_RUST_CACHE_VERSION: v0
    - name: Build
      run: cargo build --verbose --target '${{ matrix.target }}'
    - name: Run tests
      run: cargo test --verbose --target '${{ matrix.target }}'
